alias ll='ls -la'
alias gs='git status'
alias gd='git diff'
alias gl='git log --oneline -20'

alias cc='claude --dangerously-skip-permissions'
alias cck='claude --dangerously-skip-permissions --settings ~/.claude/settings-kimi.json'
alias ccx='claude --dangerously-skip-permissions --settings ~/.claude/settings-codex.json'
alias cdx='codex --yolo'
alias op='opencode'
alias pp='parallel-cli'
